name       : perl-mro-compat
version    : 0.13
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/H/HA/HAARG/MRO-Compat-0.13.tar.gz : 8a2c3b6ccc19328d5579d02a7d91285e2afd85d801f49d423a8eb16f323da4f8
license    : Artistic-2.0
component  : programming.perl
summary    : |
     mro::* interface compatibility for Perls < 5.9.5
description: |
     mro::* interface compatibility for Perls < 5.9.5
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
