name       : perl-mro-compat
version    : '0.15'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/MRO-Compat-0.15.tar.gz : 0d4535f88e43babd84ab604866215fc4d04398bd4db7b21852d4a31b1c15ef61
homepage   : https://metacpan.org/pod/MRO::Compat
license    : Artistic-2.0
component  : programming.perl
summary    : MRO::Compat - mro::* interface compatibility for Perls < 5.9.5
description: |
    The "mro" namespace provides several utilities for dealing with method resolution order and method caching in general in Perl 5.9.5 and higher.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
